import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { Poppins } from 'next/font/google'
import { Grid } from '@mui/material'
import AboutMe from './aboutme/page'
import Projects from './projects/page'
import Skills from './skills/page'

const poppins = Poppins({subsets:['latin'],
  weight: ["100","200","300","400","500","600","700","800","900"]}
);

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar/>
        <AboutMe/>
        <Projects/>
        <Skills/>
      </body>
    </html>
  )
}
